// Generated by GraphWalker (http://www.graphwalker.org)
package org.isf.vaccine.manager;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;
import org.isf.utils.exception.OHServiceException;

@Model(file = "vaccine/Vaccine.json")
public interface IVaccine {

    @Edge()
    void e_DeleteVaccine() throws OHServiceException;

    @Edge()
    void e_IsCodePresentException();

    @Edge()
    void e_FindVaccine() throws OHServiceException;

    @Vertex()
    void v_OHException();

    @Edge()
    void e_GetVaccine() throws OHServiceException;

    @Edge()
    void e_NewVaccineException();

    @Edge()
    void e_IsCodePresent() throws OHServiceException;

    @Edge()
    void e_UpdateVaccine() throws OHServiceException;

    @Vertex()
    void v_NoVaccines() throws OHServiceException;

    @Vertex()
    void v_Vaccines() throws OHServiceException;

    @Edge()
    void e_DeleteVaccineException() throws OHServiceException;

    @Edge()
    void e_FindVaccineException();

    @Edge()
    void e_NewVaccine() throws OHServiceException;

    @Edge()
    void e_Reset();

    @Edge()
    void e_UpdateVaccineException() throws OHServiceException;
	
}
